#!/usr/bin/env bash
set -e


RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

install() {
  if command -v dnf &>/dev/null;then
    sudo dnf -qy install "$@"
    sudo dnf -qy mark user "$@"
  elif command -v pacman &>/dev/null;then
    sudo pacman -S --needed --noconfirm "$@"
  elif command -v apt &>/dev/null;then
    sudo apt install -y "$@"
  fi
}

log_info() {
  echo -e "${BLUE}[INFO ]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN ]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

log_success() {
  echo -e "${PURPLE}[GGWP ]${NC} $1"
}
