#!/usr/bin/env bash
set -e


RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

install() {
  local to_install=()

  for pkg in "$@"; do
    if ! command -v "$pkg" &>/dev/null; then
      to_install+=("$pkg")
    else
      log_info "$pkg already installed, skipping"
    fi
  done

  if [ ${#to_install[@]} -eq 0 ]; then
    return 0
  fi

  log_info "Installing: ${to_install[*]}"
  if command -v dnf &>/dev/null; then
    sudo dnf -qy install "${to_install[@]}"
    sudo dnf -qy mark user "${to_install[@]}"
  elif command -v pacman &>/dev/null; then
    sudo pacman -S --needed --noconfirm "${to_install[@]}"
  elif command -v apt &>/dev/null; then
    sudo apt install -y "${to_install[@]}"
  fi
}

copr_add() {
  if ! command -v dnf &>/dev/null; then
    return 0
  fi

  if dnf copr list 2>/dev/null | grep -q "$1"; then
    log_info "copr $1 already enabled, skipping"
  else
    sudo dnf copr enable -y "$1"
  fi
}

log_info() {
  echo -e "${BLUE}[INFO ]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN ]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

log_success() {
  echo -e "${PURPLE}[GGWP ]${NC} $1"
}
