#!/usr/bin/env bash
set -e

install() {
  if command -v dnf &>/dev/null;then
    sudo dnf install -y "$@"
    sudo mark user "$@"
  elif command -v pacman &>/dev/null;then
    sudo pacman -S --needed --noconfirm "$@"
  elif command -v apt &>/dev/null;then
    sudo apt install -y "$@"
  fi
}
