[timestamps]
format = "[15:04]"

[theme]
background_color = "default"

[theme.title]
active_color = "purple"

[theme.border]
active_color = "purple"

[theme.guilds_tree]
auto_expand_folders = true
graphics = true
private_channel_color = "blue"

[theme.messages_text]
show_user_nicks = true
show_user_colors = true
reply_indicator = ">"
forwarded_indicator = "<"
author_color = "purple"
content_color = "white"
emoji_color = "green"
link_color = "blue"
attachment_color = "yellow"
