[buildPlans.Iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevka.variants]
  inherits = "ss14"

    [buildPlans.Iosevka.variants.design]
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    four = "closed-serifless"
    five = "upright-flat-serifless"
    six = "straight-bar"
    seven = "curly-serifed"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "dotted"
    capital-a = "round-top-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothed-serifless-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-j = "descending-serifed-both-sides"
    capital-k = "curly-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "closed-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "standing-serifless"
    capital-s = "serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    d = "toothed-serifless"
    f = "flat-hook-tailed"
    g = "single-storey-flat-hook-serifless"
    h = "straight-serifless"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "compact-serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-straight-serifless"
    y = "cursive-flat-hook-serifless"
    z = "curly-serifless"
    cyrl-a = "double-storey-serifed"
    cyrl-ve = "standard-interrupted-serifless"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ka = "straight-bottom-right-serifed"
    cyrl-ka = "straight-bottom-right-serifed"
    cyrl-em = "hanging-serifless"
    cyrl-capital-en = "top-left-bottom-right-serifed"
    cyrl-en = "tailed-top-left-serifed"
    cyrl-capital-er = "closed-serifless"
    cyrl-er = "eared-serifless"
    cyrl-u = "straight-serifless"
    cyrl-ef = "cursive"
    cyrl-yeri = "cursive"
    cyrl-capital-ya = "standing-serifless"
    cyrl-ya = "standing-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    asterisk = "hex-low"
    paren = "normal"
    brace = "straight"
    ampersand = "closed"
    dollar = "open-cap"
    cent = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "smooth"
    pilcrow = "high"
    decorative-angle-brackets = "middle"

[buildPlans.Iosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Iosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
