# Leader
set -g prefix C-s

# Reload config <leader>+r
unbind r
bind r source-file ~/.dotfiles/env/.config/tmux/tmux.conf

# True color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Mouse on
set -g mouse on

# motion.nvim
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R
bind-key -n M-h previous-window
bind-key -n M-j switch-client -p
bind-key -n M-k switch-client -p
bind-key -n M-l next-window
bind-key -n M-1 selectw -t 1
bind-key -n M-2 selectw -t 2
bind-key -n M-3 selectw -t 3
bind-key -n M-4 selectw -t 4
bind-key -n M-5 selectw -t 5
bind-key -n M-6 selectw -t 6
bind-key -n M-7 selectw -t 7
bind-key -n M-8 selectw -t 8
bind-key -n M-9 selectw -t 9

# clipboard
set -s set-clipboard on
setw -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi y send-keys -X copy-pipe

# Set index to 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# TPM
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.dotfiles/env/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.dotfiles/env/.config/tmux/plugins/tpm/tpm'

###
##  Theme
#

# Sarnai Colors
set -ogq @base				"#172620"
set -ogq @surface			"#21362d"
set -ogq @overlay			"#2d493d"
set -ogq @muted				"#4e7e6b"
set -ogq @subtle			"#90bbaa"
set -ogq @text				"#dfece7"
set -ogq @sarnai			"#f0c3cb"
set -ogq @anis				"#ff6b6b"
set -ogq @chatsalgan	"#e5951a"
set -ogq @els					"#cca24d"
set -ogq @uvs					"#80b946"
set -ogq @nuur				"#2b879e"
set -ogq @mus					"#9deaea"
set -ogq @yargui			"#d5b3e5"

# Messages
set -g message-style "fg=#{@chatsalgan} bg=#{@base}"
set -g message-command-style "fg=#{@els} bg=#{@base}"

# Panes
set -g pane-border-style "fg=#{@muted} bg=#{@base}"
set -g pane-active-border-style "fg=#{@sarnai} bg=#{@base}"

# Status global
set -g status-position top
set -g status-keys vi
set -g status-style "fg=#{@text} bg=#{@base}"

# Status
set -g status-left " #[fg=#{@mus} bg=#{@base}] [#S] #[fg=#{@base} bg=#{@base}]"
set -g status-left-length 20
set -g status-right ""

# Window active
set -g window-status-current-format "[#I #W#F]"
set -g window-status-current-style "fg=#{@sarnai} bg=#{@base}"

# Window inactive
set -g window-status-format "#I #W#F"
set -g window-status-style "fg=#{@muted} bg=#{@base}"
