#!/usr/bin/env bash

dots_dir="$HOME/.dotfiles"

while read -r script; do
    "$script" || echo "[WARN] $script failed."
done < <(find "$dots_dir/runs" -name "*.sh")

stow -d "$HOME/.dotfiles" -t "$HOME" env
