# Sarnai theme
# by Titembaatar

theme[main_bg]="#172620"
theme[main_fg]="#dfece7"
theme[title]="#9deaea"
theme[hi_fg]="#f0c3cb"
theme[selected_bg]="#f0c3cb"
theme[selected_fg]="#172620"
theme[inactive_fg]="#4e7e6b"
theme[proc_misc]="#f0c3cb"
theme[cpu_box]="#2b879e"
theme[mem_box]="#80b946"
theme[net_box]="#9deaea"
theme[proc_box]="#d5b3e5"
theme[div_line]="#2d493d"

theme[temp_start]="#9deaea"
theme[temp_mid]="#e5951a"
theme[temp_end]="#ff6b6b"

theme[cpu_start]="#9deaea"
theme[cpu_mid]="#e5951a"
theme[cpu_end]="#ff6b6b"

theme[free_start]="#9deaea"
theme[free_mid]="#e5951a"
theme[free_end]="#ff6b6b"

theme[cached_start]="#9deaea"
theme[cached_mid]="#e5951a"
theme[cached_end]="#ff6b6b"

theme[available_start]="#9deaea"
theme[available_mid]="#e5951a"
theme[available_end]="#ff6b6b"

theme[used_start]="#9deaea"
theme[used_mid]="#e5951a"
theme[used_end]="#ff6b6b"

theme[download_start]="#9deaea"
theme[download_mid]="#e5951a"
theme[download_end]="#ff6b6b"

theme[upload_start]="#9deaea"
theme[upload_mid]="#e5951a"
theme[upload_end]="#ff6b6b"

