console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
	newline = true

	[[blocks.segments]]
		type = 'session'
		style = 'plain'
		background = 'transparent'
		foreground = 'magenta'
		template = '{{ if not .Root }}{{ .UserName }}{{ if not .SSHSession }} {{ end }}{{ end }}'

	[[blocks.segments]]
		type = 'session'
		style = 'plain'
		background = 'transparent'
		foreground = 'red'
		template = '{{ if .Root }}{{ .UserName }}{{ if not .SSHSession }} {{ end }}{{ end }}'

	[[blocks.segments]]
		type = 'session'
		style = 'plain'
		background = 'transparent'
		foreground = 'cyan'
		template = '{{ if .SSHSession }}@{{ .HostName }}{{ end }} '

	[[blocks.segments]]
		type = 'path'
		style = 'plain'
		background = 'transparent'
		foreground = 'blue'
		template = '{{ .Path }} '
	
		[blocks.segments.properties]
			style = 'full'

	[[blocks.segments]]
		type = 'git'
		style = 'plain'
		background = 'transparent'
		foreground = 'yellow'
		template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <red>{{ if gt .Behind 0 }}⇣{{ end }}</><green>{{ if gt .Ahead 0 }}⇡{{ end }}</>'

		[blocks.segments.properties]
			branch_icon = ''
			commit_icon = '@'
			fetch_status = true

[[blocks]]
	type = 'rprompt'
	overflow = 'hidden'

	[[blocks.segments]]
		type = 'executiontime'
		style = 'plain'
		background = 'transparent'
		foreground = 'yellow'
		template = '{{ .FormattedMs }}'

		[blocks.segments.properties]
			threshold = 500

[[blocks]]
	type = 'prompt'
	alignment = 'left'
	newline = true

	[[blocks.segments]]
		type = 'text'
		style = 'plain'
		background = 'transparent'
		foreground_templates = [
			"{{if gt .Code 0}}red{{end}}",
			"{{if eq .Code 0}}cyan{{end}}",
		]
		template =';'

[transient_prompt]
	background = 'transparent'
	foreground_templates = [
		"{{if gt .Code 0}}red{{end}}",
		"{{if eq .Code 0}}cyan{{end}}",
	]
	template = '; '

[secondary_prompt]
	background = 'transparent'
	foreground = 'cyan'
	template = ';; '
