[ids]
*

[main]
capslock = overload(symbols, esc)

[symbols]
q = (
w = {
e = [
r = *
t = &
y = |
u = [
i = }
o = )
p = +

a = "
s = '
d = `
f = /
g = $
h = _
j = =
k = .
l = ,
semicolon = macro(: =)

z = \
x = !
c = #
v = %
b = ^
n = -
m = ~
