#!/usr/bin/env bash

export FZF_DEFAULT_OPTS='
  --color=fg:-1,fg+:#90bbaa,bg:-1,bg+:#21362d
  --color=hl:#f0c3cb,hl+:#ff6b6b,info:#afaf87,marker:#2b879e
  --color=prompt:#f0c3cb,spinner:#d5b3e5,pointer:#d5b3e5,header:#87afaf
  --color=border:#2d493d,label:#aeaeae,query:#d9d9d9
  --padding="1" --prompt="; " --marker="&" --pointer="*"'

