font_family      family="Iosevka"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size					16.0

# zsh
shell /usr/bin/zsh

# clipboard
copy_on_select clipboard

# theme
tab_bar_edge			bottom
include ./themes/sarnai-khavar.conf

# nvim/zenmode
allow_remote_control socket-only
listen_on unix:/tmp/kitty
